name: Sync to GitLab

on:
  push:
    branches: [ main, BaseAuth ]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git push "https://oauth2:${GITLAB_TOKEN}@gitlab.com/LienThuan04/project-graduation.git"