export enum NotificationType {
  ACCOUNT_APPROVED = 'ACCOUNT_APPROVED',
  SURVEY_PUBLISHED = 'SURVEY_PUBLISHED',
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  PROPOSAL_STATUS = 'PROPOSAL_STATUS',
  COMPLAINT_STATUS = 'COMPLAINT_STATUS',
  FEEDBACK_RESPONDED = 'FEEDBACK_RESPONDED',
  EMPLOYEE_REQUEST = 'EMPLOYEE_REQUEST',
}
